### PR TITLE
Adding packaged charts

### PR DESCRIPTION
**Pull request by arooshap**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@ericvaandering 

Could you please review this PR. Thanks

**Comment by arooshap** [comment]
@ericvaandering and for the index.yaml file, do I need to upload it on the gh-pages branch?

**Comment by arooshap** [comment]
@ericvaandering do I also need to add index.yaml file in the gh-pages branch for my repo? because if you have added the chart releaser action, this should become automated, however, I am not completely sure.

**Comment by ericvaandering** [comment]
I think we're having a miscommunication. Setup correctly, the action takes care of everything. Generating the index file, creating the TGZ files, and updating the gh-pages branch. So I'm going to just close the PR. Let me try your other suggestion about making a Rucio subdirectory for charts, but I suspect it's not going to work.

**Pull request closed without merging**
