### PR TITLE
Remove unused secret eos-krb

### PR DESCRIPTION
**Pull request by micsucmed**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
Hi @micsucmed 

I think these secrets are required to mount eos space?

**Comment by muhammadimranfarooqi** [comment]
As per doc.

https://cms-http-group.docs.cern.ch/k8s_cluster/eos/#adjusting-services-manifest-file

**Comment by micsucmed** [comment]
Hi @muhammadimranfarooqi,
I think you are right, but remember we used newdqmgui-secrets as the kerberos key? How should this be handled then?

**Comment by micsucmed** [comment]
Should we still add an eos-krb secret to the namespace along side the newdqmgui-secret?

**Comment by muhammadimranfarooqi** [comment]
Ok. Then there is no need to create a separate secrets. 

Cheers

**Comment by micsucmed** [comment]
@muhammadimranfarooqi an error of eos-krb not being found is still appearing, maybe this secret should be used by default with eos mount. I think using both secrets is necessary. Could we rollback this commit?

**Comment by muhammadimranfarooqi** [comment]
Ok. 
I have rolled back it https://github.com/dmwm/CMSKubernetes/pull/1220

**Pull request merged**
