### PR TITLE
Adjust WMCore MS manifest files to work with RPM and pypi images

### PR DESCRIPTION
**Pull request by vkuznet**
Adjust WMCore k8s manifest files to have common names for RPM based and PyPi based images (deployment procedure).

### CODE REVIEW

**Comment by amaltaro** [comment]
@vkuznet Valentin, just to make sure I understand this.

Before we can actually merge it, don't we need to ensure that the CMSWEB team is also building images for the "new" microservices under the proper tagging?

**Comment by vkuznet** [comment]
yes, that is correct, we first need a resolution of https://its.cern.ch/jira/browse/CMSKUBERNETES-208, once we'll have all new images with tag HGXXXXX in place then we can merge this PR.

**Comment by vkuznet** [comment]
We have now PR for adding new images (aliases), see https://github.com/dmwm/CMSKubernetes/pull/1266

**Comment by arooshap** [comment]
Hello @vkuznet, now we have the images with the tags `HG2212-vx` . Can we merge this PR now?

**Comment by vkuznet** [comment]
@arooshap , not yet, as I wrote in https://its.cern.ch/jira/browse/CMSKUBERNETES-208, we need an additional pieces in place:
- please update prod/preprod branches in services_config repo with rucio (and its rucio.cfg), it exists in test branch
- then you need to create rucio-secrets in all k8s clusters since this PR relies on presence of this secret
- make sure or create corresponding images for existing HGXXXX tag we use in all k8s clusters, e.g. on production cluster we have HG2211f tag, on testbed HG2212b-v2, HG2212b-v3. So, all of these tags we use in currently running pods should have these new images since if we'll need to redeploy with this PR changes the existing image should be available in testbed/prod/dev clusters.

After that we can merge this PR.

**Comment by arooshap** [comment]
Hi @vkuznet,


I have updated the prod/pre-prod branches in services_config to include the rucio secrets. These secrets are also deployed on all the dev, testbed, and prod clusters. Currently, we are using HG2212c for the testbed and HG2211f for the production cluster. I created images for both these tags for all the relevant images. With this, I have also verified this pull request by deploying a service in the dev cluster.

**Comment by vkuznet** [comment]
@arooshap , could you please tell @amaltaro which dev cluster contains newly deployed images that he can verify them. Or, @amaltaro , do you want to deploy images to testbed that we can verify all MS services?

**Comment by amaltaro** [comment]
I'd rather use one of the Dev clusters for this, given that Todor is completing the testbed validation today and another deployment can potentially disrupt the system.

**Comment by amaltaro** [comment]
@vkuznet Valentin, the `workqueue.yaml` manifest needs to be updated such that it uses the `global-workqueue` registry image, instead of workqueue.

**Comment by amaltaro** [comment]
Please also provide a description for this PR to make it easier to check things in the future.

**Comment by vkuznet** [comment]
@amaltaro , I made necessary changes for t0_reqmon/workqueue. Please review the changes and we can proceed with the merge.

**Comment by amaltaro** [comment]
Looks good to me. Thanks for providing these changes.

**Pull request merged**
