### PR TITLE
Adjusting filebeat to run as a separate pod

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
With this PR, I have applied filebeat to be run as a pod and removed from the FE DS.

**Comment by muhammadimranfarooqi** [comment]
Apart from pods logs, is there any configuration to see logs for filebeat itself?

**Comment by vkuznet** [comment]
regarding logs, it depends how you run filebeat, if it yields logs to stdout, then you should see them in k get logs <pod-name>, otherwise if it if configured to write them to file then they should be seen in a that file. Bottom line I think it is defined in its config, see https://github.com/muhammadimranfarooqi/CMSKubernetes/blob/85a48787cfa1779ffc43995ce0ef5eccbf3cb507/kubernetes/cmsweb/services/filebeat.yaml#L22

**Comment by vkuznet** [comment]
on cmsweb-k8s-services-testbed cluster you can see filebeat logs using k get logs <pod-name> -n auth

**Comment by muhammadimranfarooqi** [comment]
You mean to uncomment these lines? 

https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/preprod/filebeat/filebeat.yml#L12-14

Can you test if filebeat is working fine? 

I dont see the data in k8s-preprod

https://monit-grafana.cern.ch/d/cmswebk8s-timber/cmsweb-timber-k8s?orgId=11&refresh=5s&from=now-1h&to=now&var-system=All&var-method=All&var-api=All&var-code=All&var-metadataType=All&var-Filters=data.code%7C%3E%7C99&var-dnFilter=.*&var-copy_of_system=All&var-dbs_deployment=All&var-dbs_instance=All&var-dbs_dbs=All&var-cluster=All&var-env=k8s-preprod

**Pull request merged**
