### PR TITLE
Map statsd variables to prometheus labels

### PR DESCRIPTION
**Pull request by nsmith-**

### CODE REVIEW

**Comment by vkuznet** [comment]
Nick, please let me know explicitly when to merge since I see you're still supplying the changes. Btw, what statsd-prometheus mapping is doing? Are we going to supply Rucio metrics to Prometheus? Just in case if you didn't heart I recently setup CMS Prometheus service on k8s and if you (Rucio) team wants to plug additional metrics we can easily do that.

**Comment by nsmith-** [comment]
We've been for some time scraping metrics to cmsweb-prometheus.  If you are decommissioning that in favor of k8s, then let's talk.
This PR is ready

**Comment by ericvaandering** [comment]
It seems you should take this PR. It's just a refinement of what we are already doing, which is taking the native statsd monitoring from Rucio and translating it to Prometheus. 

This is unrelated to providing the promtheus monitoring of the k8s cluster itself you and I discussed. 

I didn't really understand the point of CMS specific prometheus in a dedicated monitoring cluster as what we get now with the scraping from MONIT seems just fine.

**Comment by vkuznet** [comment]
Let me clarify. The MONIT does not have Prometheus, what we have in MONIT is a ability to add Prometheus source. All the Prometheus metrics we got are from server we run on dedicated VM. Then we add this source in MONIT such that we can build grafana dashboards out of it. And, now I migrated Prometheus from custom VM to k8s. This cluster will contain Prometheus and other components we may need for monitoring. Therefore if you want Prometheus metrics it will be our service, but MONIT grafana. If you're talking about metrics you push to ES in MONIT it is different story. In particular, you asked me to add these servers to Prometheus 
```
[
  {
    "targets": [ "cms-rucio-stats-dev.cern.ch" ],
    "labels": {
      "env": "dev",
      "job": "rucio-dev"
    }
  },
  {
    "targets": [ "cms-rucio-stats-testbed.cern.ch" ],
    "labels": {
      "env": "testbed",
      "job": "rucio-testbed"
    }
  },
  {
    "targets": [ "cms-rucio-stats-sync.cern.ch" ],
    "labels": {
      "env": "sync",
      "job": "rucio-sync"
    }
  },
  {
    "targets": [ "cms-rucio-stats-int.cern.ch" ],
    "labels": {
      "env": "int",
      "job": "rucio-int"
    }
  }
]
```
and our (CMS) not MONIT Prometheus scrape them.

**Comment by ericvaandering** [comment]
Ah, I thought monit scrapes these directly.

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Dec 13, 2019, at 08:34, Valentin Kuznetsov <notifications@github.com> wrote:

﻿

Let me clarify. The MONIT does not have Prometheus, what we have in MONIT is a ability to add Prometheus source. All the Prometheus metrics we got are from server we run on dedicated VM. Then we add this source in MONIT such that we can build grafana dashboards out of it. And, now I migrated Prometheus from custom VM to k8s. This cluster will contain Prometheus and other components we may need for monitoring. Therefore if you want Prometheus metrics it will be our service, but MONIT grafana. If you're talking about metrics you push to ES in MONIT it is different story. In particular, you asked me to add these servers to Prometheus

[
  {
    "targets": [ "cms-rucio-stats-dev.cern.ch" ],
    "labels": {
      "env": "dev",
      "job": "rucio-dev"
    }
  },
  {
    "targets": [ "cms-rucio-stats-testbed.cern.ch" ],
    "labels": {
      "env": "testbed",
      "job": "rucio-testbed"
    }
  },
  {
    "targets": [ "cms-rucio-stats-sync.cern.ch" ],
    "labels": {
      "env": "sync",
      "job": "rucio-sync"
    }
  },
  {
    "targets": [ "cms-rucio-stats-int.cern.ch" ],
    "labels": {
      "env": "int",
      "job": "rucio-int"
    }
  }
]


and our (CMS) not MONIT Prometheus scrape them.

**Pull request merged**
