### PR TITLE
Fix a MariaDB related bug, caused by the previous PR.

### PR DESCRIPTION
**Pull request by todor-ivanov**
This is a PR meant to resolve a bug caused by a typo in this PR:  https://github.com/dmwm/CMSKubernetes/pull/1451

### CODE REVIEW

**Review by amaltaro — COMMENTED** [review]
These changes look good to me. However, there are still 2 comments - in the other PR - that deserve further discussion:
1) please fix a bad indentation
2) creation of the database when cleaning up MariaDB.

I suggest to try to converge on those things before getting these changes merged in.

**Comment by todor-ivanov** [comment]
@amaltaro I added the requested changes and yet another one. 
I remembered in the MariaDB container, you asked to have an interactive user confirmation for cleaning the relational database  from the prompt. And also noticed we were missing the respective confirmation when cleaning the databases  from the agent. Hence I added it for both MariaDB and Oracle with my latest commit. Please take another look. 

BTW, Here is how the current prompt  looks like:
```
(WMAgent-2.3.0) [cmst1@vocms0290:current]$ manage clean-mysql

clean_mysql: THE CURRENT OPERATIONS WILL WIPE OUT THE  DATABASE.
clean_mysql: Continue? [n]: y
clean_mysql: ...
clean_mysql: You still have 5 sec. to cancel before we proceed.

clean_mysql: Dropping MySQL DB... 

```

**Review by amaltaro — APPROVED** [review]
Looks good to me, thanks Todor.

**Comment by todor-ivanov** [comment]
Hi @amaltaro, 

while testing the above changes I noticed we already have moved to MDB_USER and MDB_PASS environment variables in the MAriaDB container..... which means these are  already the ones supposed  to be present in the WMAgent.Secrrets file as well: 
https://github.com/dmwm/CMSKubernetes/blob/0e9277d98a1feba8f9e6b0bc20c5fb6e1f0ef4c9/docker/pypi/wmagent-mariadb/manage#L173 

But the wmagent container was still bound to MYSQL_* environnment variables. So I took advantage of having this not merged yet and mad the proper change for the wmagent container as well. I did test it and it is fine now. Please take a look befor I merge it. 

BTW. We still have to fully retire any `mysql*` commands and code variable names once we decide to move to a MariaDB version 10.11. I'll create  the relevant GH issue.

**Comment by todor-ivanov** [comment]
Thanks @amaltaro  Merging this one now

**Pull request merged**
