### PR TITLE
Update WMCore microservices docker image name

### PR DESCRIPTION
**Pull request by amaltaro**
Changes related to the WMCore migration to pypi packaging, currently being discussed in:
https://github.com/dmwm/WMCore/issues/11354

This should not be merged until we can properly test these new docker image.

### CODE REVIEW

**Comment by vkuznet** [comment]
Alan, I'm not sure it is backward compatible, since we use RPM based image `reqmgr2ms` for all services, while pypi images are unique to the service. So if we'll merge this then we'll break RPM based image until we create similar images like `reqmgr2ms-output` in RPM land as well. What we need to complement this PR is to create alias images `reqmgr2ms` RPM based image should have alias (or clone) `reqmgr2ms-output`, etc.

**Comment by amaltaro** [comment]
I do not think we need to make it backwards compatible. Reason why I said: "This should not be merged until we can properly test these new docker image."

IMO, we test things out and if we are happy with them, we go ahead and merge it. We are not making these changes planning to go back anyways.

**Comment by vkuznet** [comment]
@amaltaro , I think we can merge this PR now since we do have both RPM and pypi based images which you proposed to use in this PR, are you agree?

**Comment by amaltaro** [comment]
@vkuznet yes Valentin, I think we can merge this now. Thanks

**Review by vkuznet — APPROVED** [review]

**Pull request merged**
