### PR TITLE
HPA for dbs

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by vkuznet** [comment]
You only created dbs HPA declaration but did not create metric declaration for prometheus adapter. It should be defined here:
https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/monitoring/prometheus/adapter/prometheus_adapter.yml
Please define it there, for more info see https://github.com/Cloud-PG/prometheus-hpa/tree/master guide

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

I have included rule in prometheus adapter configmap and redeployed it. However, the error persists. Could you please have a look. Thanks

**Comment by vkuznet** [comment]
So, let's see what you did:
```
# get configmap
k get cm -n monitoring
NAME                           DATA   AGE
logstash                       2      60m
prometheus-adapter-configmap   1      72m

# get pods in monitoring
kpod monitoring
NAME                                  READY   STATUS    RESTARTS   AGE
kube-eagle-b5d7fcd69-lvlp2            1/1     Running   0          4d
logstash-8655b4974-nz7m2              1/1     Running   0          60m
prometheus-6c56d48d6b-rft2b           1/1     Running   0          4d
prometheus-adapter-868b7c64d4-k5crs   1/1     Running   0          66m

# get hpa 
k get hpa -A
NAMESPACE   NAME               REFERENCE                    TARGETS        MINPODS   MAXPODS   REPLICAS   AGE
dbs         dbs-global-r-hpa   Deployment/dbs-global-r      <unknown>/1k   5         10        8          69m
http        httpgo-hpa         Deployment/httpgo-exporter   290m/1500m     1         3         1          3d19h
```
As you can see by looking at AGE values. You created first prometheus-adapter, then HPA and then prometheus-adapter configmap. The adapter reads configmap, therefore your configmap changes never used by your running adapter. The order matters here. Please redo everything in proper order, i.e. create a new map (for that you'll need to delete existing one, and use the changes in this PR) because it contains adapter metrics definitions. Then redeploy adapter, then redeploy HPA.

**Comment by muhammadimranfarooqi** [comment]
Even after deploying with the particular order, the error persists.

```
[mimran@lxplus765]~/CMSKubernetes-testbed/CMSKubernetes/kubernetes/cmsweb% kubectl get cm -n monitoring
NAME                           DATA   AGE
logstash                       2      84m
prometheus-adapter-configmap   1      12m
[mimran@lxplus765]~/CMSKubernetes-testbed/CMSKubernetes/kubernetes/cmsweb% kubectl get pods -n monitoring
NAME                                  READY   STATUS    RESTARTS   AGE
kube-eagle-b5d7fcd69-lvlp2            1/1     Running   0          4d
logstash-8655b4974-nz7m2              1/1     Running   0          84m
prometheus-6c56d48d6b-rft2b           1/1     Running   0          4d
prometheus-adapter-868b7c64d4-vqbp5   1/1     Running   0          9m43s
[mimran@lxplus765]~/CMSKubernetes-testbed/CMSKubernetes/kubernetes/cmsweb% kubectl get hpa -A
NAMESPACE   NAME               REFERENCE                    TARGETS        MINPODS   MAXPODS   REPLICAS   AGE
dbs         dbs-global-r-hpa   Deployment/dbs-global-r      <unknown>/1k   5         10        8          9m
http        httpgo-hpa         Deployment/httpgo-exporter   150m/1500m     1         3         1          3d20h
```

**Comment by vkuznet** [comment]
Ahh, that's a different story now, if you'll check the hpa you'll see:
```
k describe hpa -n dbs dbs-global-r-hpa
Name:                                                                         dbs-global-r-hpa
Namespace:                                                                    dbs
Labels:                                                                       <none>
Annotations:                                                                  CreationTimestamp:  Fri, 24 Jul 2020 17:42:34 +0200
Reference:                                                                    Deployment/dbs-global-r
Metrics:                                                                      ( current / target )
  "dbs_global_exporter_process_open_fds" on Job/dbs-global-r (target value):  <unknown> / 1k
Min replicas:                                                                 5
Max replicas:                                                                 10
Deployment pods:                                                              8 current / 0 desired
Conditions:
  Type           Status  Reason                 Message
  ----           ------  ------                 -------
  AbleToScale    True    SucceededGetScale      the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetObjectMetric  the HPA was unable to compute the replica count: unable to get metric dbs_global_exporter_process_open_fds: Job on dbs dbs-global-r/unable to fetch metrics from custom metrics API: the server could not find the metric dbs_global_exporter_process_open_fds for jobs.batch dbs-global-r
Events:
  Type     Reason                        Age                  From                       Message
  ----     ------                        ----                 ----                       -------
  Warning  FailedComputeMetricsReplicas  28m (x12 over 30m)   horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get object metric value: unable to get metric dbs_global_exporter_process_open_fds: Job on dbs dbs-global-r/unable to fetch metrics from custom metrics API: the server could not find the metric dbs_global_exporter_process_open_fds for jobs.batch dbs-global-r
  Warning  FailedGetObjectMetric         42s (x119 over 30m)  horizontal-pod-autoscaler  unable to get metric dbs_global_exporter_process_open_fds: Job on dbs dbs-global-r/unable to fetch metrics from custom metrics API: the server could not find the metric dbs_global_exporter_process_open_fds for jobs.batch dbs-global-r
```
So it complains that it can find job metric. If you'll look closely how I did it for httpgo-exporter you'll see this notice:
```
        # must specify for hpa, otherwise it will be job="kubernetes-pods"
        # assigned automatically by prometheus
        job: httpgo-exporter
```
at https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/services/httpgo-exporter.yaml#L34-L36
So for prometheus adapter we need job label. Therefore you need similar job label for service you're trying to hpa's. I think you need to add `jobs: dbs-global-r` into DBS manifest file.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Thanks Valentin. Now it is working.

**Pull request merged**
