### PR TITLE
Add MSUnmerged .yaml

### PR DESCRIPTION
**Pull request by todor-ivanov**

### CODE REVIEW

**Comment by todor-ivanov** [comment]
FYI: @amaltaro

**Comment by amaltaro** [comment]
It looks perfect to me, thanks, Todor. @muhammadimranfarooqi could you please have a look at this as well?

**Comment by todor-ivanov** [comment]
Hi @muhammadimranfarooqi @vkuznet ,
Are we going to merge this one? because I need to add some more commits on top of this one in order to make the service deployed on different pods.

**Comment by vkuznet** [comment]
@todor-ivanov, sorry I missed this one, now it is merged.

**Comment by todor-ivanov** [comment]
Thanks @vkuznet for the prompt reaction!

**Pull request merged**
