### PR TITLE
Adjusting resources for reqmon

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 
FYI

**Comment by amaltaro** [comment]
looks good to me. Can you please provide instructions on how to change these requirements if we test things in a very small VM?

**Comment by muhammadimranfarooqi** [comment]
@amaltaro 

You can edit resources using this command after deployment. 

`kubectl edit deployment reqmon -n dmwm`

Adjust resources and save. After that pods will be recreated with new configuration.

**Comment by amaltaro** [comment]
Would you have this command in any of those documentations (dev or testbed)? I'm pretty sure I will either forget or not know what to do when I start playing with kubernetes and find myself failing to start reqmon pods.

**Pull request merged**
