### PR TITLE
Updating cmsweb image

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by vkuznet** [comment]
Muhammd, I don't know if `20200531` tag is appropriate. Did you rebuild the new cmsweb image now? If so, why do you assign this tag? I don't see any correlation between cc7 tags and cmsweb ones, and using current date tag seems more appropriate. Please clarify.

**Comment by muhammadimranfarooqi** [comment]
Valentin,

For, `20200531` I used '20200504' earlier. This one is the latest tag https://hub.docker.com/r/cern/cc7-base/tags

I am creating new images with this tag.

**Comment by vkuznet** [comment]
Well, as I wrote to you I moved fetch-crl now into cmsweb as of today and I would expect that you'll build cmsweb image first and then use its new tag in all services images. Is it not the case now?

**Comment by muhammadimranfarooqi** [comment]
https://hub.docker.com/r/cmssw/cmsweb/tags

cmsweb image has been built. Now I am building all services images.

**Comment by muhammadimranfarooqi** [comment]
New cmsweb image contains fetch-crl.

**Comment by vkuznet** [comment]
ok.

**Pull request merged**
