### PR TITLE
Update wmcore-dev

### PR DESCRIPTION
**Pull request by d-ylee**
Migrated final changes from dmwm/WMCore-Jenkins Docker image to docker/pypi/wmcore-dev

Added a README and updated build instructions.

### CODE REVIEW

**Comment by d-ylee** [comment]
I have also included more changes to fix https://github.com/dmwm/WMCore/issues/12187

**Review by khurtado — COMMENTED** [review]
Hi Dennis,

This is looking good to me. 
Can you add a bit more information on the `make push`? 
E.g.: This will push your built image into the `wmcore-dev` repository inside the CERN registry`cmsweb` project. Special account privileges granted by the cmsweb team are required to do this.

**Comment by d-ylee** [comment]
I separated the build step to both `make push` and `make push-stable`. I also had to copy the script directories some stuff due to changes in how the scripts are pulled in. I will make changes in https://github.com/dmwm/WMCore-Jenkins:

1. [ ] Move TestScripts and ContainerScripts to the root directory of WMCore-Jenkins repo.
2. [ ] Delete WMCore-Jenkins/docker/wmcore-dev, as these are moved to CMSKubernetes
3. [ ] Edit entrypoint to point to copy the proper directories
4. [ ] Make sure paths in scripts are using the proper scripts
  * WMCore-PR-test/Jenkinsfile: https://github.com/dmwm/WMCore-Jenkins/blob/5c3f9bb218736855c073523543aa1280f03d1ee6/WMCore-PR-test/Jenkinsfile#L95
  * WMCore-unittests-baseline/Jenkinsfile: https://github.com/dmwm/WMCore-Jenkins/blob/5c3f9bb218736855c073523543aa1280f03d1ee6/WMCore-unittests-baseline/Jenkinsfile#L109
  * WMCore-PR-pylint/Jenkinsfile: https://github.com/dmwm/WMCore-Jenkins/blob/5c3f9bb218736855c073523543aa1280f03d1ee6/WMCore-PR-pylint/Jenkinsfile#L57
  * TestScripts/test-wmcorepy3.sh
  * TestScripts/pylintPRTest.sh
  * TestScripts/env_unittests.sh
  * ContainerScripts...
  * etc.

**Comment by d-ylee** [comment]
This goes along with dmwm/WMCore#12187 and dmwm/WMCore-Jenkins#17

**Comment by d-ylee** [comment]
wmcore-dev:0.2.0-stable is now pushed to the registry and is being used by Jenkins on the d-ylee/WMCore-Jenkins fix-12187 branch.

**Pull request merged**
