### PR TITLE
New labels in new version of k8s

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**
@vkuznet 

Could you please review this PR for new labels in new version of k8s. I followed this doc https://clouddocs.web.cern.ch/containers/quickstart.html#custom-clusters 
and get following results 

[mimran@lxplus765]~% openstack coe cluster template show -f json kubernetes-1.17.2-1 |
    jq --raw-output '.labels | to_entries |
    map("--labels \(.key)=\"\(.value)\"") | join(" ")'
--labels kubecontroller_options="--feature-gates=CSINodeInfo=true,CSIDriverRegistry=true"
--labels kube_tag="v1.17.2"
--labels cgroup_driver="cgroupfs" 
--labels admission_control_list="NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority" 
--labels ingress_controller="traefik" 
--labels manila_version="v0.3.0" 
--labels cvmfs_csi_enabled="true" 
--labels metrics_server_enabled="true" 
--labels kubeapi_options="--feature-gates=CSINodeInfo=true,CSIDriverRegistry=true --runtime-config=storage.k8s.io/v1alpha1=true" 
--labels etcd_tag="3.3.17" 
--labels cephfs_csi_enabled="true" 
--labels cephfs_csi_version="cern-csi-1.0-2" 
--labels influx_grafana_dashboard_enabled="false" 
--labels calico_ipv4pool_ipip="CrossSubnet" 
--labels cloud_provider_tag="v1.17.0" 
--labels heapster_enabled="false" 
--labels tiller_enabled="true" 
--labels manila_enabled="true" 
--labels use_podman="true" 
--labels calico_ipv4pool="10.100.0.0/16" 
--labels kube_csi_enabled="true" 
--labels kube_csi_version="cern-csi-1.0-2" 
--labels kubelet_options="--feature-gates=CSINodeInfo=true,CSIDriverRegistry=true" 
--labels container_infra_prefix="gitlab-registry.cern.ch/cloud/atomic-system-containers/" 
--labels cvmfs_csi_version="v1.0.0" 
--labels heat_container_agent_tag="train-stable-1"

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Specially, I did not find this label  --labels autoscaler_tag="v1.15.2"  in new k8s version.

**Comment by vkuznet** [comment]
the changes look fine to me but I better keep autoscalers as we'll need them. Please find out which label to use this case.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

I did not find autoscalers in new k8s version. Furthermore, I am trying to create cluster but it is failing after timeout. I'll open a ticket for this.

**Comment by vkuznet** [comment]
we'll use labels from SNOW ticket,
https://cern.service-now.com/service-portal/view-request.do?n=RQF1524622

closing this one

**Pull request closed without merging**
