### PR TITLE
Adding rules for crabcache

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Could you please review this PR. After applying this, alerts did not appear in http://cmsweb-k8s-testbedsrv.cern.ch:30000/alerts

**Comment by vkuznet** [comment]
please describe what you did when you say after deploying. Here are the steps required to enable it:
- recreate prometheus-secrets with new file
- restart prometheus pod
In you case if you login to prometheus pod and look-up its config you'll find this:
```
cat /etc/prometheus/prometheus.yaml
....
rule_files:
  - "/etc/prometheus/das.rules"
  - "/etc/prometheus/dbs.rules"
  - "/etc/prometheus/mongodb.rules"
  - "/etc/prometheus/crabserver.rules"
  - "/etc/prometheus/reqmgr2.rules"
  - "/etc/prometheus/k8s.rules"
```
SO, somehow you didn't update prometheus.yaml in your prometheus-secrets file. Just recreate prometheus-secrets with all new files and restart prometheus pod.

**Comment by muhammadimranfarooqi** [comment]
I deleted monitoring and applied again. 

The prometheus-secrets have `crabcache.rules` while inside pod of prometheus this rule does not exist. But I have appended rule in monitoring/prometheus/services/prometheus.yaml

**Comment by muhammadimranfarooqi** [comment]
I think its issue with deployment script. I'll fix this. Thanks

**Comment by muhammadimranfarooqi** [comment]
http://cmsweb-k8s-testbedsrv.cern.ch:30000/alerts I can see now.

**Pull request merged**
