### PR TITLE
Adding bash in exporters

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by vkuznet** [comment]
why do we need bash? Can we use sh instead?

**Comment by vkuznet** [comment]
if we'll rely on sh then we can use alpine as a image (which is minimal and also secure).

**Comment by muhammadimranfarooqi** [comment]
First, I tried without bash and was getting error for bash in `process_monitor.sh` script for configuring exporter as sidecar.

**Comment by vkuznet** [comment]
so, instead of jumping to change docker file, just fix process_monitoring.sh to work with plain sh instead of bash. Then you can safely switch in dockerfile from bash to sh.

**Pull request merged**
