### PR TITLE
Move monitoring images to new registry, bump alpine versions and upgrade promxy, loki

### PR DESCRIPTION
**Pull request by mrceyhun**
Related with CMSKUBERNETES-133

- I built `promxy` image with the latest release, however I did not test it yet. Please not merge.
- Other builds are autamatically triggered and built by GH workflows in CMSMonitoring. They will be tested.  
- @muhammadimranfarooqi `loki` is already in [cmsweb cern registry](https://registry.cern.ch/harbor/projects/1771/repositories/loki) . It has a new release: `v2.5.0` and I added it to this commit. Please inform me, if you don't want to use new loki version and then I can rollback it.

fyi @leggerf @brij01

### CODE REVIEW

**Comment by vkuznet** [comment]
+1

**Comment by mrceyhun** [comment]
This PR exceeded its initial purpose because of necessities. 

- All cmsmonitoring images are built and pushed to cern registry
- All new images are applied in the services and deployed in mon, ha1, ha2 and agg clusters
- Some dockerfiles required refactoring for the base GoLang image version, some of them required to use new base images and they are applied. When it exists, I used cmsweb cern registry image (like httpgo), others are built and pushed to cmsmonitoring
- Some secrets are arranged with new changes and cron-proxy/cron-kerberos CJ are applied and tested.

Deployed services are:

```
- crons/cron-kerberos.yaml
- crons/cron-proxy.yaml
- services/cmsmon-vol.yaml
- services/httpgo.yaml
- services/ha/httpgo.yaml
- services/hdfs-exporter-eos.yaml
- services/http-exp-wmstatssrv.yaml
- services/http-exporter-arucio.yaml
- services/http-exporter-cric.yaml
- services/http-exporter-detox.yaml
- services/http-exporter-dmytro.yaml
- services/http-exporter-mcm.yaml
- services/http-exporter-mss.yaml
- services/http-exporter-rucio.yaml
- services/http-exporter-unified.yaml
- services/http-exporter-wmstats.yaml
- services/http-exporter.yaml
- services/karma.yaml
- services/nats-sub-dbs.yaml
- services/nats-sub-exitcode.yaml
- services/nats-sub-reqmgr2.yaml
- services/nats-sub-stats.yaml
- services/nats-sub-t1.yaml
- services/nats-sub-t2.yaml
- services/promxy.yaml
- services/sqoop.yaml
- services/agg/victoria-metrics-long.yaml
- services/agg/victoria-metrics.yaml
```

---

Some issues are noticed:
- `- services/log-clustering.yaml` has a "requirements.txt" conflict, it will be fixed in its git repo.
- [http_exporter.go](https://github.com/dmwm/cmsweb-exporters/blob/master/http_exporter.go) tries to renew proxy even `-proxyfile` parameter is not provided like in `http-exporter-rucio.yaml` which does not need proxy secret. That's why k8s pod produces error logs. New issue will be open.
- `services/nats-sub.yaml` is not deployed and is almost similar with `services/nats-sub-exitcode.yaml`. Can we delete it if it'll not be deployed?

References:
- `k get pods -A | grep -v "magnum-tiller" | grep -v "kube-system"` in mon, ha1, ha2, agg clusters
-  https://registry.cern.ch/harbor/projects/1782/repositories

fyi @vkuznet @leggerf @brij01

**Comment by mrceyhun** [comment]
Ahh, forget to mention, I modified `karma` Dockerfile with the latest upstream [karma/Dockerfile](https://github.com/prymitive/karma/blob/main/Dockerfile)

**Comment by brij01** [comment]
> This PR exceeded its initial purpose because of necessities.
> 
>     * All cmsmonitoring images are built and pushed to cern registry
> 
>     * All new images are applied in the services and deployed in mon, ha1, ha2 and agg clusters
So.. all these changes in this PR are already deployed in these clusters ? 
can you please point me to these images in the registry. 
> 
>     * Some dockerfiles required refactoring for the base GoLang image version, some of them required to use new base images and they are applied. When it exists, I used cmsweb cern registry image (like httpgo), others are built and pushed to cmsmonitoring
> 
>     * Some secrets are arranged with new changes and cron-proxy/cron-kerberos CJ are applied and tested.
> 
> 
> Deployed services are:
> 
> ```
> - crons/cron-kerberos.yaml
> - crons/cron-proxy.yaml
> - services/cmsmon-vol.yaml
> - services/httpgo.yaml
> - services/ha/httpgo.yaml
> - services/hdfs-exporter-eos.yaml
> - services/http-exp-wmstatssrv.yaml
> - services/http-exporter-arucio.yaml
> - services/http-exporter-cric.yaml
> - services/http-exporter-detox.yaml
> - services/http-exporter-dmytro.yaml
> - services/http-exporter-mcm.yaml
> - services/http-exporter-mss.yaml
> - services/http-exporter-rucio.yaml
> - services/http-exporter-unified.yaml
> - services/http-exporter-wmstats.yaml
> - services/http-exporter.yaml
> - services/karma.yaml
> - services/nats-sub-dbs.yaml
> - services/nats-sub-exitcode.yaml
> - services/nats-sub-reqmgr2.yaml
> - services/nats-sub-stats.yaml
> - services/nats-sub-t1.yaml
> - services/nats-sub-t2.yaml
> - services/promxy.yaml
> - services/sqoop.yaml
> - services/agg/victoria-metrics-long.yaml
> - services/agg/victoria-metrics.yaml
> ```
> 
> Some issues are noticed:
> 
>     * `- services/log-clustering.yaml` has a "requirements.txt" conflict, it will be fixed in its git repo.
> 
>     * [http_exporter.go](https://github.com/dmwm/cmsweb-exporters/blob/master/http_exporter.go) tries to renew proxy even `-proxyfile` parameter is not provided like in `http-exporter-rucio.yaml` which does not need proxy secret. That's why k8s pod produces error logs. New issue will be open.
> 
>     * `services/nats-sub.yaml` is not deployed and is almost similar with `services/nats-sub-exitcode.yaml`. Can we delete it if it'll not be deployed?
> 
> 
> References:
> 
>     * `k get pods -A | grep -v "magnum-tiller" | grep -v "kube-system"` in mon, ha1, ha2, agg clusters
> 
>     * https://registry.cern.ch/harbor/projects/1782/repositories
> 
> 
> fyi @vkuznet @leggerf @brij01

**Comment by mrceyhun** [comment]
@brij01 you can find all Dockerfile changes in https://github.com/dmwm/CMSKubernetes/pull/1018/files under "docker" folder. images have same name with CMSKubernetes/docker folder and you can easily distinguish new changes in https://registry.cern.ch/harbor/projects/1782/repositories

Yes, except for "log-clustering", I deployed all services, their secrets(like proxy-secrets in ha1/http namespace),  checked logs, checked if data flow is ok(i.e. prometheus for http exporters). If you notice any problem in services, please inform me. 

A review of Dockerfiles would be great.

**Comment by brij01** [comment]
@mrceyhun  I went though the dockerfile changes as well as registry images 
Except for the critical vulnerabilities shown in the registry, everything looks good. But this is not particularly related with this PR so this is ready to be merged. 
Thanks for this important work.

**Review by vkuznet — APPROVED** [review]
For the record, all images in registry can be easily found if you'll click on search icon and type your pattern, e.g. to find cmsmonitoring just type cms and it will lead to https://registry.cern.ch/harbor/projects/1782/repositories page.

**Pull request merged**
