### PR TITLE
Adding deploy-secrets.sh script

### PR DESCRIPTION
**Pull request by muhammadimranfarooqi**

### CODE REVIEW

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , I look at the script and I would like to make few suggestions:
- I doubt that dev teams should have access to certificates and hmac on cluster, but yes we need those in secrets, therefore we have two solutions
  - separate certificates/hmac into own secrets and allow developers only to create secrets associated with their services
  - load certificates/hmac from cluster itself, e.g. from proxy-secrets, and automatically use them within this script to create service secrets

Therefore, I  suggest that script should only take ns, service, and configuration path. Please see how we can change script such that we can use either approach. The more secure one is to separate certificates/hmac from service  configuration files because the former should be done by cmsweb operator (whoever who create a cluster), and it will mostly require changes in manifest files. The second approach is easier to implement but it will keep security flaw that someone can obtain robot certificate and/or hmac.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Ok. I have adjusted this script as per your instruction. I'll try to implement first option in deploy.sh script  with another PR.

**Comment by vkuznet** [comment]
The script requires proper checks of configuration area, please add something like this to the begining of the script:
```
if [ !-d $conf/$srv ]; then
  echo "Unable to locate $conf/$srv, please provide proper directory structure like <configuration>/<service>/<files>"
  sys.Exit(1)
fi
```

**Comment by muhammadimranfarooqi** [comment]
Ok. I have adjusted this.

There is one issue with the first option. We can't mount more than one secrets to /etc/secrets area. I tried to create cluster with hmac and robot and tried to mount them in /etc/secrets area but get error. Since all secrets are in this area, how should we handle this issue.

**Comment by vkuznet** [comment]
What you can do is to mount individual files within mounted area I think. First, mount service secrets, then use similar approach how we mount hostcert.pem and hostkey.pem in FE, see https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/daemonset/frontend-ds.yaml#L52

**Comment by muhammadimranfarooqi** [comment]
I tried like this below: 

```
       - name: hmac
          mountPath: /etc/secrets/hmac
          readOnly: true
 ```
 and 
```
      - name: hmac
        secret:
            secretName: robot-secrets
```
In this way hmac directory is created inside /etc/secrets which contains files of robot-secrets.

**Comment by vkuznet** [comment]
try to figure out, ask Spyros, try with emptyDir, see services/auth-proxy-server.yaml, use intermediate container, may be we'll use config-maps, etc.

**Comment by muhammadimranfarooqi** [comment]
I found one way of resolving this issue with mounting secrets to some path i.e. /etc/robot
and then copying files from /etc/robot/ to /data/srv/current/auth/dbs/ using configmap in manifest file like this. 
```
    cp /etc/robot/robotkey.pem /data/srv/current/auth/dbs/dmwm-service-key.pem
    cp /etc/robot/robotcert.pem /data/srv/current/auth/dbs/dmwm-service-cert.pem
    cp /etc/robot/hmac /data/srv/current/auth/dbs/
```
and 

```
        - name: robot
          mountPath: /etc/robot
          readOnly: true
``` 

and 

```
      - name: robot
        secret:
            secretName: robot-secrets
```

Does it sound good?

**Comment by vkuznet** [comment]
yes, that's fine but it will require adjusting service manifest files to know which path to copy the files and we need to verify that it works for all services (including new ones I made for das-server, etc. which I didn't really follow standard VM based deployment approach anymore).

**Comment by muhammadimranfarooqi** [comment]
Do we need hmac and dmwm certificates for das / wmarchive?

Infact if I see from VM, only following services use dmwm certificates. 

```
[cmsweb@vocms0731 srv]$ find /data/srv/current/auth/* -name "dmwm-service-cert.pem"
/data/srv/current/auth/acdcserver/dmwm-service-cert.pem
/data/srv/current/auth/crabserver/dmwm-service-cert.pem
/data/srv/current/auth/reqmgr/dmwm-service-cert.pem
/data/srv/current/auth/reqmgr2/dmwm-service-cert.pem
/data/srv/current/auth/reqmgr2ms/dmwm-service-cert.pem
/data/srv/current/auth/reqmon/dmwm-service-cert.pem
/data/srv/current/auth/t0_reqmon/dmwm-service-cert.pem
/data/srv/current/auth/workqueue/dmwm-service-cert.pem
```

while hmac is for couch dependent apps. 

```
[cmsweb@vocms0731 ~]$ find /data/srv/current/auth/* -name "*hmac*"
/data/srv/current/auth/bigcouch/hmackey.ini
/data/srv/current/auth/couchdb/hmackey.ini
```

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

Although, it can be done like example I posted above using configmap, but we need `hmac` in `/etc/secrets` area. Nothing can be copied to `/etc/secrets` from another mount  area as I get error of read only file system even after setting readOnly option to false in the manifest files.

I noticed there are lot of dependencies of `/etc/secrets/hmac` i.e. `run.sh` script for all services and also for livenessprobe. If we mount certificates/hmac in `/etc/secrets/default` then adjustment in `run.sh` script and manifest files need to be done.

**Comment by vkuznet** [comment]
@muhammadimranfarooqi , I suggest we do this in two phases:
Phase 1.

- change all run.sh scripts to add additional blocks to use new location for robot certs `/etc/robots` and hmac `/etc/hmac`, e.g.
```
# overwrite host PEM files in /data/srv area
if [ -f /etc/secrets/robotkey.pem ]; then
    sudo cp /etc/secrets/robotkey.pem /data/srv/current/auth/$srv/dmwm-service-key.pem
    sudo cp /etc/secrets/robotcert.pem /data/srv/current/auth/$srv/dmwm-service-cert.pem
    sudo chown $USER.$USER /data/srv/current/auth/$srv/dmwm-service-key.pem
    sudo chown $USER.$USER /data/srv/current/auth/$srv/dmwm-service-cert.pem
fi
# HERE IS new block with different location but identical content
# overwrite host PEM files in /data/srv area
if [ -f /etc/robots/robotkey.pem ]; then
    sudo cp /etc/robots/robotkey.pem /data/srv/current/auth/$srv/dmwm-service-key.pem
    sudo cp /etc/robotss/robotcert.pem /data/srv/current/auth/$srv/dmwm-service-cert.pem
    sudo chown $USER.$USER /data/srv/current/auth/$srv/dmwm-service-key.pem
    sudo chown $USER.$USER /data/srv/current/auth/$srv/dmwm-service-cert.pem
fi
....
# overwrite header-auth key file with one from secrets
if [ -f /etc/secrets/hmac ]; then
    mkdir -p /data/srv/current/auth/wmcore-auth
    if [ -f /data/srv/current/auth/wmcore-auth/header-auth-key ]; then
        sudo rm /data/srv/current/auth/wmcore-auth/header-auth-key
    fi
    sudo cp /etc/secrets/hmac /data/srv/current/auth/wmcore-auth/header-auth-key
    sudo chown $USER.$USER /data/srv/current/auth/wmcore-auth/header-auth-key
    mkdir -p /data/srv/current/auth/$srv
    if [ -f /data/srv/current/auth/$srv/header-auth-key ]; then
        sudo rm /data/srv/current/auth/$srv/header-auth-key
    fi
    sudo cp /etc/secrets/hmac /data/srv/current/auth/$srv/header-auth-key
    sudo chown $USER.$USER /data/srv/current/auth/$srv/header-auth-key
fi
# HERE IS new block with new location but identical content
# overwrite header-auth key file with one from /etc/hmac location
if [ -f /etc/hmac/hmac ]; then
    mkdir -p /data/srv/current/auth/wmcore-auth
    if [ -f /data/srv/current/auth/wmcore-auth/header-auth-key ]; then
        sudo rm /data/srv/current/auth/wmcore-auth/header-auth-key
    fi
    sudo cp /etc/hmac/hmac /data/srv/current/auth/wmcore-auth/header-auth-key
    sudo chown $USER.$USER /data/srv/current/auth/wmcore-auth/header-auth-key
    mkdir -p /data/srv/current/auth/$srv
    if [ -f /data/srv/current/auth/$srv/header-auth-key ]; then
        sudo rm /data/srv/current/auth/$srv/header-auth-key
    fi
    sudo cp /etc/hmac/hmac /data/srv/current/auth/$srv/header-auth-key
    sudo chown $USER.$USER /data/srv/current/auth/$srv/header-auth-key
fi
```
- rebuild images
- prepare new k8s manifest changes to use new locations, here we need three pieces:
  - new secrets for `/etc/robots`
  - new secrets for `/etc/hnac`
  - new livenessProbes to use new hmac location
- redeploy using either `/etc/secrets` or `/etc/robots` and `/etc/hmac` locations.

Doing this way we can it will be backward compatible and we can test things using either location.

Phase 2.
Then in second phase you'll remove  original blocks in run.sh script which uses `/etc/secrets`, rebuild images again and redeploy them to all clusters.

Of course, everything can be done in one phase but it will be more load on you to make all changes and redeploy everything at once.

I think this worth doing since we'll separate admin and user configs and eventually have better control on all of them.

**Comment by muhammadimranfarooqi** [comment]
@vkuznet 

This PR has been tested and can be merged. I'll make another PR for all other services.

**Pull request merged**
