### PR TITLE
Use new dmwm-base tag in pypi images

### PR DESCRIPTION
**Pull request by vkuznet**
The tag `dmwm-base:pypi-20230125` provides `process_exporter`, `cpy_exporter` and `monitor.sh` for all pypi based images. For details please see https://github.com/dmwm/WMCore/issues/11454

### CODE REVIEW

**Review by amaltaro — APPROVED** [review]
Thanks Valentin. It looks like you covered them all.

**Comment by amaltaro** [comment]
Once it gets merged, I will trigger a WMCore rc2 release.

**Comment by vkuznet** [comment]
ok, merged, please trigger WMCore rc2 release.

**Comment by amaltaro** [comment]
`2.1.7rc2` WMCore images should now be available, in case you want to give them a try in your dev cluster.

**Pull request merged**
