### PR TITLE
Add resource limit to condor-cpu-eff

### PR DESCRIPTION
**Pull request by mrceyhun**
@vkuznet  Optimum values are given as resource limits after a few tests.

### CODE REVIEW

**Comment by mrceyhun** [comment]
@vkuznet If this works fine, we may migrate all acronjobs of cmsmonit to k8s?

**Comment by vkuznet** [comment]
@mrceyhun , even though I merged the PR, I didn't realize until now that it resides in kubernetes area. Please note, that under kubernetes area we put directories which contains manifest for entire cluster, like cmsweb or monitoring clusters. Please relocate  condor-cpu-eff under kubernetes/monitoring/services area where it belongs.

**Comment by mrceyhun** [comment]
@Valentin Kuznetsov ***@***.***> Should I keep it as a folder
or keep just the yaml file? If yes and we deploy it to the monitoring
cluster, should I edit deploy.sh and deploy-secrets.sh?

**Comment by vkuznet** [comment]
it depends how we'll deploy it. If we'll deploy it within monitoring cluster then you'll only need to move yaml file into services and adjust deploy script. But if we'll decide to deploy it into separate `spider` cluster then we'll create new dir for that cluster and setup there services and deploy script. So far I suggest to move it under monitoring. Once we'll gain experience how much resources it needs we can decide if we'll run it in separate cluster or not.

**Pull request merged**
